export const PHARMACY_CATEGORIES = [
  { id: '1', label: 'Antibiotics' },
  { id: '2', label: 'Analgesics (Painkillers)' },
  { id: '3', label: 'Antipyretics' },
  { id: '4', label: 'Antivirals' },
  { id: '5', label: 'Antifungals' },
  { id: '6', label: 'Supplements & Vitamins' },
  { id: '7', label: 'Cardiovascular Meds' },
  { id: '8', label: 'Anti-Diabetics' },
  { id: '9', label: 'Respiratory Meds' },
  { id: '10', label: 'Gastrointestinal' },
  { id: '11', label: 'Dermatologicals' },
  { id: '12', label: 'ENT Preparation' },
  { id: '13', label: 'Ophthalmic Prep' },
  { id: '14', label: 'Reproductive Health' },
  { id: '15', label: 'Vaccines/Biologicals' },
  { id: '16', label: 'First Aid & Medical Supplies' },
  { id: '17', label: 'Antiprotozoal' },
  { id: '18', label: 'Antihistamines' },
  { id: '19', label: 'Hormonal Prep' },
  { id: '20', label: 'General Health' },
];
